app:
  report_mode: incremental

notification:
  telegram:
    enabled: true

platforms:
  - name: 微博
    enabled: true
  - name: 知乎
    enabled: true
  - name: 抖音
    enabled: true
  - name: 财联社
    enabled: true
  - name: 华尔街见闻
    enabled: true
  - name: 百度
    enabled: true
  - name: 今日头条
    enabled: true
  - name: 澎湃
    enabled: true
  - name: bilibili
    enabled: true
